### ISSUE TITLE
Not working on Asus Tablet with Android 5

### ISSUE THREAD

**Issue by tkskoapps** [luxiliu/LabelLayout#3]
Hi!
It seems that it doesnt work on Android 5 or perhaps in the Asus Android 5.
I tried with the example app from the store and implemeting a demo label in my app and it doesnt show...
I tried it in my phone with Android 7 and it works.. so i think is something with Android 5...
ty

**Comment by luxiliu** [comment]
Hi,

What's the model of your device, and what's the version of Android system?  Can you provide a screenshot?

Thanks

**Comment by tkskoapps** [comment]
![device-2017-01-06-190536](https://cloud.githubusercontent.com/assets/8340175/21734675/5fa4cab8-d443-11e6-9c24-c330a0738800.png)

here is your demo app! as you can see, is not showing the label.

The model is ASUS MeMO Pad 7 (ME170C). Its running Android 5.0 stock from Asus (there is no custom roms for this model).

thanks!

**Comment by luxiliu** [comment]
It's a bug. I'm going to fix it asap.

**Comment by luxiliu** [comment]
Fixed in new release 1.0.1

**Comment by tkskoapps** [comment]
i can confirm that is working!
thanks for your time and this great library!
I was using fixed images before and now the labels looks great!

**Comment by luxiliu** [comment]
Thanks for your support!
